trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    cd CursoAWS_Proyectos/python/ec2
    git pull
    cdk deploy --require-approval never
  displayName: 'Deploy EC2 instance'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    pip install awscli --upgrade
    aws configure set aws_access_key_id $(AWS_ACCESS_KEY_ID)
    aws configure set aws_secret_access_key $(AWS_SECRET_ACCESS_KEY)
    aws configure set region $(AWS_REGION)
  displayName: 'Configure AWS CLI'

- script: |
    cdk bootstrap aws://992382590076/us-east-1
    cdk deploy -y
  displayName: 'Deploy CDK stacks'