trigger:
- main  # Rama que activará la ejecución del pipeline

pool:
  vmImage: 'ubuntu-latest'

variables:
  AWS_REGION: 'us-east-1'  # Especifica tu región de AWS
  AWS_DEFAULT_REGION: 'us-east-1'  # Región por defecto de AWS

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'  # Usa la versión de Python 3.x
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install aws-cdk.core boto3  # Instala AWS CDK y boto3
  displayName: 'Instalar dependencias de Python'

- script: |
    echo "[default]" > ~/.aws/credentials
    echo "aws_access_key_id = $(AWS_ACCESS_KEY_ID)" >> ~/.aws/credentials
    echo "aws_secret_access_key = $(AWS_SECRET_ACCESS_KEY)" >> ~/.aws/credentials
    echo "[default]" > ~/.aws/config
    echo "region = $(AWS_REGION)" >> ~/.aws/config
  displayName: 'Configurar credenciales de AWS'

- script: |
    python python/ec2/cdk.out/app.py  # Ejecuta tu script de Python con CDK
  displayName: 'Ejecutar script de Python CDK'

# Asegúrate de que las variables AWS_ACCESS_KEY_ID y AWS_SECRET_ACCESS_KEY estén configuradas en las variables de entorno del pipeline de manera segura
